---
- name: Setup Webserver1 (Created by https://github.com/Itsmide)
  hosts: webserver1
  become: yes
  remote_user: root

  tasks:

  - name: Update Machine
    shell: sudo apt update

  - name: Install Apache Server (Created by https://github.com/Itsmide)
    apt:
      name: apache2
      state: present

  - name: set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display Web Server Name
    shell: echo '<h1><center>Welcome to Itsmide Project 1.<br>First Server.</center></h1>' > /var/www/html/index.html


- name: Setup Webserver2 (Created by https://github.com/Itsmide)
  hosts: webserver2
  become: yes
  remote_user: root

  tasks:

  - name: Update Machine
    shell: sudo apt update

  - name: Install Apache Server (Created by https://github.com/Itsmide)
    apt:
      name: apache2
      state: present

  - name: set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display Web Server Name
    shell: echo '<h1><center>Welcome to Itsmide Project 2.<br>Second Server.</center></h1>' > /var/www/html/index.html


- name: Setup Webserver3 (Created by https://github.com/Itsmide)
  hosts: webserver3
  become: yes
  remote_user: root

  tasks:

  - name: Update Machine
    shell: sudo apt update

  - name: Install Apache Server (Created by https://github.com/Itsmide)
    apt:
      name: apache2
      state: present

  - name: set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display Web Server Name
    shell: echo '<h1><center>Welcome to Itsmide Project 3.<br>Third Server.</center></h1>' > /var/www/html/index.html
